name: CI

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup pythons' versions
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies
      run: |
        python3 -m pip install pip==22.0.4
        pip3 install -r requirements.txt

    - name: Test with pytest
      run: |
        python -m pytest --cov=catchment.models tests/test_models.py